parameters:
    brs_security.authentication_handler: BRS\SecurityBundle\Handler\AuthenticationHandler
    
services:
    authentication_handler:
        class:  %brs_security.authentication_handler%
        arguments:  [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    ajax_authentication_handler:
        class: BRS\SecurityBundle\Handler\AjaxAuthenticationHandler
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException, priority: 1000 }
    